train_file: ["./SAMM_datasets/jsons/train.json"]
val_file: ["./SAMM_datasets/jsons/val.json"]
images_file: ./SAMM_datasets

bert_config: 'configs/config_bert.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size_train: 8
batch_size_val: 32
temp: 0.07
queue_size: 65536
momentum: 0.995
alpha: 0.4
max_words: 50
label_smoothing: 0.0

loss_MAC_wgt: 0.1
loss_cncl_wgt: 0.1
loss_pat_wgt: 0.3
loss_2cls_wgt: 1.3
loss_bbox_wgt: 0.1
loss_giou_wgt: 0.1
loss_tok_wgt: 1
loss_mcls_wgt: 1

# settings for batch_size = 4 * 8 (gpu numbers * per_gpu_batch_size)
optimizer: {opt: adamW, lr: 5e-6, lr_img: 2.5e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 5e-6, epochs: 50, min_lr: 2.5e-6, decay_rate: 1, warmup_lr: 2.5e-7, warmup_epochs: 10, cooldown_epochs: 0}








